### PR TITLE
Fix/promise defer

### PR DESCRIPTION
**Pull request by matmar10**
From hunterloftis:'fix/promise-defer'

### CODE REVIEW

**Comment by matmar10** [comment]
Adds fixes from #44

**Comment by matmar10** [comment]
Fixed #43

**Comment by JAertgeerts** [comment]
@matmar10 this change Will allow newer versions of node, should be added to CI

**Comment by matmar10** [comment]
@JAertgeerts noted; will add to travis

**Comment by matmar10** [comment]
@JAertgeerts do you have a recommendation on versions to add to the test suite ?

**Comment by JAertgeerts** [comment]
7, 8, 9 and 10?

**Pull request merged**
