### PR TITLE
pass messageTtl to amqplib

### PR DESCRIPTION
**Pull request by haircuttedfreak**
I think this is the intention here.  Use the messageTTL pass on the options and send as the expiration on the message publish.

### CODE REVIEW

**Comment by createproblem** [comment]
:+1:

**Comment by Spidy88** [comment]
Please merge! This is a big need for my application as well. I was about to do the same thing. PR seems solid!

**Comment by hunterloftis** [comment]
Hey guys, sorry for the huge delay. Have been distracted by other projects; I'll go through the pending PRs here this week.

**Comment by Spidy88** [comment]
Fantastic! Thanks @hunterloftis . Was a bit worried this became another unmaintained project (and it is so useful!)

**Comment by Spidy88** [comment]
Bump

**Comment by Akamaozu** [comment]
Also thinking messageTtl default should be undefined, not 1000. Messages would persist by default and expire only if you indicate a lifespan duration. 

Logical, plus it seems weird passing undefined as an option. My thoughts.

That being said, thanks so much for jackrabbit, @hunterloftis! 
Helped me get started with rabbitmq really quickly.

:+1:

**Pull request merged**
